# Generated by scripts/generate_yo61_configs.sh
# Imports every managed yo61 repo and its terraform resources into state.
# Remove this file after running stategraph tf apply tfplan.json.

# agent-team-topologies
import {
  to = module.org_yo61.module.repo["agent-team-topologies"].github_repository.this
  id = "agent-team-topologies"
}
import {
  to = module.org_yo61.module.repo["agent-team-topologies"].github_repository_collaborators.this
  id = "agent-team-topologies"
}
import {
  to = module.org_yo61.module.repo["agent-team-topologies"].github_repository_ruleset.this["default_branch"]
  id = "agent-team-topologies:16783295"
}
import {
  to = module.org_yo61.module.repo["agent-team-topologies"].github_repository_vulnerability_alerts.this["this"]
  id = "agent-team-topologies"
}
# commitlint-github-action
import {
  to = module.org_yo61.module.repo["commitlint-github-action"].github_repository.this
  id = "commitlint-github-action"
}
import {
  to = module.org_yo61.module.repo["commitlint-github-action"].github_repository_collaborators.this
  id = "commitlint-github-action"
}
