# Generated by scripts/generate_import_blocks.sh
# Imports every managed ycst-org-uk repo and its terraform resources into state.
# Remove this file after running task apply.

# ycst-dashboard
import {
  to = module.org_ycst_org_uk.module.repo["ycst-dashboard"].github_repository.this
  id = "ycst-dashboard"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-dashboard"].github_repository_collaborators.this
  id = "ycst-dashboard"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-dashboard"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-dashboard"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-dashboard"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-dashboard"
}
# ycst-events
import {
  to = module.org_ycst_org_uk.module.repo["ycst-events"].github_repository.this
  id = "ycst-events"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-events"].github_repository_collaborators.this
  id = "ycst-events"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-events"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-events"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-events"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-events"
}
# ycst-governance-report
import {
  to = module.org_ycst_org_uk.module.repo["ycst-governance-report"].github_repository.this
  id = "ycst-governance-report"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-governance-report"].github_repository_collaborators.this
  id = "ycst-governance-report"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-governance-report"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-governance-report"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-governance-report"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-governance-report"
}
# ycst-member-card
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-card"].github_repository.this
  id = "ycst-member-card"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-card"].github_repository_collaborators.this
  id = "ycst-member-card"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-card"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-member-card"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-card"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-member-card"
}
# ycst-member-discounts
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-discounts"].github_repository.this
  id = "ycst-member-discounts"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-discounts"].github_repository_collaborators.this
  id = "ycst-member-discounts"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-discounts"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-member-discounts"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-member-discounts"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-member-discounts"
}
# ycst-protected-files
import {
  to = module.org_ycst_org_uk.module.repo["ycst-protected-files"].github_repository.this
  id = "ycst-protected-files"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-protected-files"].github_repository_collaborators.this
  id = "ycst-protected-files"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-protected-files"].github_repository_vulnerability_alerts.this["this"]
  id = "ycst-protected-files"
}
import {
  to = module.org_ycst_org_uk.module.repo["ycst-protected-files"].github_repository_dependabot_security_updates.this["this"]
  id = "ycst-protected-files"
}
