#!/usr/bin/env bash
# Generate data/yo61/<repo>.yaml files matching every yo61 repo's current
# settings on GitHub, plus an imports-yo61.tf file that imports the same set
# into Terraform state.
#
# YAML is emitted *sparsely*: only fields where the live value diverges from
# the modules/github-repo default are written. The module defaults are the
# source of truth — see modules/github-repo/variables.tf.
#
# Usage:
#   scripts/generate_yo61_configs.sh                # all yo61 repos
#   scripts/generate_yo61_configs.sh repo1 repo2    # subset
#
# Requires: gh (authenticated), jq, bash 4+.

set -euo pipefail

ORG=yo61
DATA_DIR="data/${ORG}"
IMPORTS_FILE="imports-${ORG}.tf"

mkdir -p "${DATA_DIR}"

# Map a GitHub API collaborator object to a single terraform-github-provider
# permission string. Prefers the newer `role_name` field; falls back to the
# legacy `permissions` boolean object.
permission_from_collaborator() {
  local json="$1"
  local role
  role=$(jq -r '.role_name // empty' <<<"${json}")
  if [[ -z "${role}" ]]; then
    if [[ "$(jq -r '.permissions.admin' <<<"${json}")" == "true" ]]; then
      role=admin
    elif [[ "$(jq -r '.permissions.maintain' <<<"${json}")" == "true" ]]; then
      role=maintain
    elif [[ "$(jq -r '.permissions.push' <<<"${json}")" == "true" ]]; then
      role=write
    elif [[ "$(jq -r '.permissions.triage' <<<"${json}")" == "true" ]]; then
      role=triage
    else
      role=read
    fi
  fi
  case "${role}" in
    admin)    echo admin ;;
    maintain) echo maintain ;;
    write)    echo push ;;
    triage)   echo triage ;;
    read|*)   echo pull ;;
  esac
}

# Collect repo names: from CLI args, or via gh repo list.
if [[ $# -gt 0 ]]; then
  REPOS=("$@")
else
  mapfile -t REPOS < <(gh repo list "${ORG}" --limit 500 --json name --jq '.[].name' | sort)
fi

# Begin imports file.
{
  printf '# Generated by scripts/generate_yo61_configs.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Imports every yo61 repo and its associated terraform resources."
  echo "# Remove this file after running stategraph tf apply tfplan.json."
  echo
} > "${IMPORTS_FILE}"

total=${#REPOS[@]}
count=0
for name in "${REPOS[@]}"; do
  count=$((count + 1))
  printf '[%d/%d] %s\n' "${count}" "${total}" "${name}" >&2

  repo_json=$(gh api "repos/${ORG}/${name}")
  collab_json=$(gh api "repos/${ORG}/${name}/collaborators?affiliation=direct&per_page=100")

  # Vulnerability alerts: 204 = enabled, 404 = disabled.
  if gh api -i "repos/${ORG}/${name}/vulnerability-alerts" 2>/dev/null | head -n1 | grep -q '204'; then
    vuln=true
  else
    vuln=false
  fi

  # Issue count via GraphQL — used to decide whether to keep has_issues enabled.
  issue_count=$(gh api graphql \
    -f query='query($o:String!,$r:String!){repository(owner:$o,name:$r){issues{totalCount}}}' \
    -F "o=${ORG}" -F "r=${name}" \
    --jq '.data.repository.issues.totalCount' 2>/dev/null || echo 0)
  issue_count=${issue_count:-0}

  # Extract every field once.
  description=$(jq -r '.description // ""' <<<"${repo_json}")
  homepage_url=$(jq -r '.homepage // ""' <<<"${repo_json}")
  visibility=$(jq -r '.visibility' <<<"${repo_json}")
  default_branch=$(jq -r '.default_branch // ""' <<<"${repo_json}")
  archived=$(jq -r '.archived' <<<"${repo_json}")
  is_template=$(jq -r '.is_template' <<<"${repo_json}")
  has_issues_api=$(jq -r '.has_issues' <<<"${repo_json}")
  has_projects=$(jq -r '.has_projects' <<<"${repo_json}")
  has_wiki=$(jq -r '.has_wiki' <<<"${repo_json}")
  has_discussions=$(jq -r '.has_discussions' <<<"${repo_json}")
  allow_merge_commit=$(jq -r '.allow_merge_commit' <<<"${repo_json}")
  allow_squash_merge=$(jq -r '.allow_squash_merge' <<<"${repo_json}")
  allow_rebase_merge=$(jq -r '.allow_rebase_merge' <<<"${repo_json}")
  allow_auto_merge=$(jq -r '.allow_auto_merge' <<<"${repo_json}")
  allow_update_branch=$(jq -r '.allow_update_branch' <<<"${repo_json}")
  delete_branch_on_merge=$(jq -r '.delete_branch_on_merge' <<<"${repo_json}")
  merge_commit_message=$(jq -r '.merge_commit_message // "PR_TITLE"' <<<"${repo_json}")
  merge_commit_title=$(jq -r '.merge_commit_title // "MERGE_MESSAGE"' <<<"${repo_json}")
  squash_commit_message=$(jq -r '.squash_merge_commit_message // "COMMIT_MESSAGES"' <<<"${repo_json}")
  squash_commit_title=$(jq -r '.squash_merge_commit_title // "COMMIT_OR_PR_TITLE"' <<<"${repo_json}")

  # has_issues: only enable if API says it's enabled AND the repo has issues.
  if [[ "${has_issues_api}" == "true" && "${issue_count}" -gt 0 ]]; then
    has_issues=true
  else
    has_issues=false
  fi

  # Write the YAML — sparse: only fields that diverge from module defaults.
  yaml_file="${DATA_DIR}/${name}.yaml"
  {
    echo "---"
    echo "name: ${name}"
    [[ -n "${description}"  ]] && jq -nr --arg s "${description}"  '"description: "  + ($s | @json)'
    [[ -n "${homepage_url}" ]] && jq -nr --arg s "${homepage_url}" '"homepage_url: " + ($s | @json)'
    [[ "${visibility}"             != "private"            ]] && echo "visibility: ${visibility}"
    [[ -n "${default_branch}" && "${default_branch}" != "main" ]] && echo "default_branch: ${default_branch}"
    [[ "${archived}"               == "true"               ]] && echo "archived: true"
    [[ "${is_template}"            == "true"               ]] && echo "is_template: true"
    [[ "${has_issues}"             == "true"               ]] && echo "has_issues: true"
    [[ "${has_projects}"           == "true"               ]] && echo "has_projects: true"
    [[ "${has_wiki}"               == "true"               ]] && echo "has_wiki: true"
    [[ "${has_discussions}"        == "true"               ]] && echo "has_discussions: true"
    [[ "${allow_merge_commit}"     == "false"              ]] && echo "allow_merge_commit: false"
    [[ "${allow_squash_merge}"     == "false"              ]] && echo "allow_squash_merge: false"
    [[ "${allow_rebase_merge}"     == "false"              ]] && echo "allow_rebase_merge: false"
    [[ "${allow_auto_merge}"       == "true"               ]] && echo "allow_auto_merge: true"
    [[ "${allow_update_branch}"    == "false"              ]] && echo "allow_update_branch: false"
    [[ "${delete_branch_on_merge}" == "false"              ]] && echo "delete_branch_on_merge: false"
    # Commit-message fields only relevant when the matching merge style is allowed.
    [[ "${allow_merge_commit}" == "true"  && "${merge_commit_message}"  != "PR_TITLE"           ]] && echo "merge_commit_message: ${merge_commit_message}"
    [[ "${allow_merge_commit}" == "true"  && "${merge_commit_title}"    != "MERGE_MESSAGE"      ]] && echo "merge_commit_title: ${merge_commit_title}"
    [[ "${allow_squash_merge}" == "true"  && "${squash_commit_message}" != "COMMIT_MESSAGES"    ]] && echo "squash_merge_commit_message: ${squash_commit_message}"
    [[ "${allow_squash_merge}" == "true"  && "${squash_commit_title}"   != "COMMIT_OR_PR_TITLE" ]] && echo "squash_merge_commit_title: ${squash_commit_title}"
    [[ "${vuln}"               == "true"                                                        ]] && echo "vulnerability_alerts: true"

    user_count=$(jq 'length' <<<"${collab_json}")
    if [[ "${user_count}" -gt 0 ]]; then
      echo "collaborators:"
      echo "  users:"
      jq -c '.[]' <<<"${collab_json}" | while read -r u; do
        login=$(jq -r '.login' <<<"${u}")
        perm=$(permission_from_collaborator "${u}")
        printf '    - { username: %s, permission: %s }\n' "${login}" "${perm}"
      done
    fi
  } > "${yaml_file}"

  # Append imports.
  {
    echo "# ${name}"
    echo "import {"
    echo "  to = module.org_${ORG}.module.repo[\"${name}\"].github_repository.this"
    echo "  id = \"${name}\""
    echo "}"
    echo "import {"
    echo "  to = module.org_${ORG}.module.repo[\"${name}\"].github_repository_vulnerability_alerts.this"
    echo "  id = \"${name}\""
    echo "}"
    user_count=$(jq 'length' <<<"${collab_json}")
    if [[ "${user_count}" -gt 0 ]]; then
      echo "import {"
      echo "  to = module.org_${ORG}.module.repo[\"${name}\"].github_repository_collaborators.this"
      echo "  id = \"${name}\""
      echo "}"
    fi
    echo
  } >> "${IMPORTS_FILE}"
done

echo "Done. ${total} repos. YAML in ${DATA_DIR}/, imports in ${IMPORTS_FILE}." >&2
